ignores:
  - udev-rules
  - config
  - base
filters:
  tags:
    include:
      - "^[0-9]{2}$"
      - "^[0-9]{2}-(.*)"
      - "^([a-z]+)$"
    exclude:
      - "([0-9]{8})"
      - "\\.sig$"
      - "^pr-.*"
